### ISSUE TITLE
An error ocurred while trying to start process 'msedge' 

### ISSUE THREAD

**Issue by AlwaysBuyCheap** [adriancs2/HTML-PDF-Edge#2]
I get the following error when running PDF.GeneratePdf
`System.ComponentModel.Win32Exception: 'An error occurred trying to start process 'msedge' with working directory 'C:\Users\xxx\source\repos\xxx\xxx\xxx\bin\Debug\net6.0'. The system cannot find the file specified.'`

**Comment by adriancs2** [comment]
most probably Microsoft Edge is not installed in the operating system

**Comment by AlwaysBuyCheap** [comment]
Yes it was. Eitherway I found another solution to the problem I had so I don't need it anymore. If you need info about the bug reopen it. Thanks
